### ISSUE TITLE
Add ipadic paths for macOS if installed via Homebrew on Apple silicon

### ISSUE THREAD

**Issue by elmimmo** [Ajatt-Tools/mecab_controller#5]
The [path for ipadic if installed via `brew install mecab-ipadic`](https://github.com/Ajatt-Tools/mecab_controller/blob/ce9027e625b5afa00eb8a6b0d6e9d939157ca9fa/basic_mecab_controller.py#L32) in the code is correct only for Intel-based Macs. On Apple silicon, that would default to `/opt/homebrew/lib/mecab/dic/ipadic/`.

Likewise, if mecab itself had been installed via `brew install mecab`, subsequently installing mecab-ipadic-neologd by following [its install instructions](https://github.com/neologd/mecab-ipadic-neologd#how-to-installupdate-mecab-ipadic-neologd) (since as of today there is no Homebrew formula to install it with `brew`) will leave the dictionary installed at:

* `/usr/local/lib/mecab/dic/mecab-ipadic-neologd/` if on an Intel-based Mac
* `/opt/homebrew/lib/mecab/dic/mecab-ipadic-neologd/` if on an Apple silicon based Mac.

neither of which are contemplated in the code.

**Comment by tatsumoto-ren** [comment]
The additional path was added in #4. Apparently, the author didn't know that other locations are possible. 

Is it okay if I simply append the following to the list?

```
/opt/homebrew/lib/mecab/dic/mecab-ipadic-neologd/
/opt/homebrew/lib/mecab/dic/ipadic/
/usr/local/lib/mecab/dic/mecab-ipadic/
```

**Comment by elmimmo** [comment]
I presume that would indeed be OK, but I made a mistake in one of the paths and edited the issue to correct it after your reply. The three extra paths should be:

```
/usr/local/lib/mecab/dic/mecab-ipadic-neologd
/opt/homebrew/lib/mecab/dic/ipadic
/opt/homebrew/lib/mecab/dic/mecab-ipadic-neologd
```
